# Generated by Django 5.0.3 on 2024-03-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='external_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
