# Generated by Django 5.0.3 on 2024-03-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='external_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
